url: http://www.sweetfromsu.com
baseurl: 

# Site settings
title: Sweets From Su
email: iwantasweetfromsu@gmail.com
description: "The best and sweetest homemade cakes that you will find!"


# Team names, titles and social links
people:
- name: Susana Madruga
  pic: 1
  position: Our Sweet Cook
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #

- name: Filipe Afonso
  pic: 2
  position: IT Guy
  social:
    - title: twitter
      url: https://twitter.com/FilipeAfonso
    - title: linkedin
      url: https://ie.linkedin.com/in/filipeafonso
    - title: globe
      url: http://www.fafonso.com/
    - title: github
      url: https://github.com/fafonso

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: google-plus
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: 

# Build settings
markdown: kramdown
permalink: pretty